name = "DobotMagician"
uuid = "eb17b914-a2e5-45e7-813f-e6fb2969af31"
authors = ["David AW Barton"]
version = "0.1.0"

[compat]
julia = "1.4"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
