name = "DobotMagician"
uuid = "eb17b914-a2e5-45e7-813f-e6fb2969af31"
authors = ["David AW Barton"]
version = "0.1.0"

[deps]
DocStringExtensions = "ffbed154-4ef7-542d-bbb7-c09d3a79fcae"
LibSerialPort = "a05a14c7-6e3b-5ba9-90a2-45558833e1df"

[compat]
DocStringExtensions = "0.8"
LibSerialPort = "0.4"
julia = "1.4"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
